lib/LoanRequest/Entity/LoanRequest.php
lib/LoanRequest/Factory/LoanRequestFactory.php

- Display product in Merchant BackOffice (AppReport and LoanRequests)
- Accompanies the following Application/Branches:
- **Baseline** / display-product-merchant-backoffice
- **Cleopatra** / display-product-merchant-backoffice
- **Merchant-Back-Office** / display-product-merchant-backoffice
[Delivers#90294736]
**[BlockedBy#90294732]**

display product merchant backoffice

---

lib/LoanRequest/Entity/LoanRequest.php
lib/LoanRequest/Entity/LoanRequestInterface.php
lib/LoanRequest/Factory/LoanRequestFactory.php
lib/LoanRequest/MakeRequest.php

- Added extra fields to loan request Objects, Factories and Repositories for Merchant Back-Office Loan Request Report
- Merchant Back-Office, Merchant Back-Office Baseline Bump, Merchant Back-Office PayBreak SDK Bump, Cleopatra Migration
[Delivers#96286624]

Loan request report

---

composer.json
src/ApiClient/ApiClientFactoryInterface.php
src/ApiClient/ProviderApiClient.php
src/Entities/Application/CancellationEntity.php
src/Entities/ApplicationEntity.php
src/Gateways/ApplicationGateway.php
src/Gateways/CreditInfoGateway.php
src/Gateways/InstallationGateway.php
src/Gateways/IpsGateway.php
src/Gateways/MerchantGateway.php
src/Gateways/PartialRefundGateway.php
src/Gateways/SettlementGateway.php
src/SdkException.php

- Added *Cancellation* object to *Application*
- Random standards fixes
[Delivers#105664280] 4/5

Cancellation fee

---

src/Gateways/InstallationGateway.php
tests/Gateways/ApplicationGatewayTest.php
tests/Gateways/InstallationGatewayTest.php

- Added product functionality for an installation to `InstallationGateway`

Product functionality for installation gateway

---

src/Entities/Application/FinanceEntity.php
src/Entities/Product/CommissionEntity.php
src/Entities/Product/MerchantCommissionEntity.php
src/Entities/ProductEntity.php

- Added Commission Entity
- Added Commission to Finance Entity

Commission changes

---

src/Entities/Application/AddressEntity.php
src/Entities/Application/ApplicantEntity.php
src/Entities/Application/CancellationEntity.php
src/Entities/Application/CustomerEntity.php
src/Entities/Application/FinanceEntity.php
src/Entities/Application/FulfilmentEntity.php
src/Entities/Application/OrderEntity.php
src/Entities/Application/ProductsEntity.php
src/Entities/ApplicationEntity.php
src/Entities/GroupEntity.php
src/Entities/IpsEntity.php
src/Entities/PartialRefundEntity.php
src/Entities/Product/MerchantCommissionEntity.php
src/Entities/ProductEntity.php

- Removed types from all abstract entities

Removed types from all entities

---

src/Entities/Application/OrderEntity.php
src/Gateways/ProductGateway.php

- Get Credit Info for a Product

GetCredit info for a product

---

src/Gateways/ApplicationGateway.php
tests/Gateways/ApplicationGatewayTest.php

- Added `getApplicationCreditInfo` call on `ApplicationGateway`
[Delivers [#126121685](https://www.pivotaltracker.com/story/show/126121685)]

Credit info for app call

---

src/Gateways/ApplicationGateway.php

- Add gateway calls for Merchant Payments
[#125524631](https://www.pivotaltracker.com/story/show/125524631)

Merchant payments

---

src/Gateways/ApplicationGateway.php

- Changed `Merchant Payments` URL's

Changes to name

---

src/Gateways/ApplicationGateway.php
tests/Gateways/ApplicationGatewayTest.php

- Add 'Get Application History' method to `ApplicationGateway`
Delivers [#126577079](https://www.pivotaltracker.com/story/show/126577079)

Application Status History

---

src/Entities/GroupEntity.php

- Added `GroupEntity:: setProducts(array)`
Part of [127177411](https://www.pivotaltracker.com/story/show/127177411)

Added `GroupEntity:: setProducts(array)`

---

src/Gateways/ProductGateway.php

- Add gateway method to get products by group

Get Products by Group

---

src/Gateways/SettlementGateway.php

- Adding aggregate settlement api call
Requires `PayBreak/basket` update.
[Delivers #130356905](https://www.pivotaltracker.com/story/show/130356905)

Aggregate Settlement Report

---

src/Entities/Installation/FeaturesEntity.php
src/Entities/InstallationEntity.php

- Added `FeaturesEntity`
[Delivers [#131806137](https://www.pivotaltracker.com/story/show/131806137)]

Installation

---

src/ApiClient/ProviderCsvApiClient.php
src/Gateways/SettlementCsvGateway.php

- Including aggregate settlement report csv api call 
[Delivers #134525555](https://www.pivotaltracker.com/story/show/134525555)

Hotfix csv client

---

src/Entities/Application/FulfilmentEntity.php
src/Gateways/ApplicationGateway.php

- Added *Fulfilment Reference* to fulfilment call
[Delivers [#135529307](https://www.pivotaltracker.com/story/show/135529307)]

Fulfilment

---

src/Gateways/ProductGateway.php

- Added `listProducts` API to SDK
- Added `orderProducts ` API to SDK
Requires https://github.com/PayBreak/merchant-api/pull/78
[Delivers #132143811](https://www.pivotaltracker.com/story/show/132143811)

Product ordering sdk api

---

src/Entities/ApplicationEntity.php
src/Gateways/DocumentGateway.php
tests/Gateways/DocumentGatewayTest.php

- Added document gateway to enable downloading the agreement and pre-agreement of an application
[Delivers: [#139542975](https://www.pivotaltracker.com/story/show/139542975)]

Add document gateway

---

composer.json
src/ApiClient/ProviderApiClient.php
src/ApiClient/ProviderCsvApiClient.php
src/Gateways/AbstractGateway.php
src/Gateways/ApplicationGateway.php
src/Gateways/PartialRefundGateway.php
tests/Gateways/ApplicationGatewayTest.php
tests/Gateways/InstallationGatewayTest.php
tests/Gateways/MerchantGatewayTest.php

- Use `PayBreak\ApiClient` instead of `Wnowicki\Generic\ApiClient`
Delivers https://www.pivotaltracker.com/story/show/143560655

Wnowicki api client refactor

---

src/Gateways/DocumentGateway.php

- Added exception handling on `getAvailableDocuments` (150168401)
[Delivers [#150168401](https://www.pivotaltracker.com/story/show/150168401)]

Hotfix documents

---

src/Entities/Product/MerchantFeesEntity.php

- Added field to **MerchantFeesEntity** to allow `clawback_subsidy_refund_percentage` to pass through (152104370)
Delivers [#152104370](https://www.pivotaltracker.com/story/show/152104370)

[3/6] Liability - Merchant Clawback Charges & Refunds (Add LC fee to entity)

---

.scrutinizer.yml
.travis.yml

- Scrutinizer config (154392323) (153057789)
[Delivers [#154392323](https://www.pivotaltracker.com/story/show/154392323) [#153057789](https://www.pivotaltracker.com/story/show/153057789)]

Scrutinizer [12/13]

---

.scrutinizer.yml
src/Gateways/SettlementGateway.php
tests/Gateways/SettlementGatewayTest.php

- `getAggregateSettlementReports` call to the settlement gateway (#157183787)
[Delivers [#157183787](https://www.pivotaltracker.com/story/show/157183787)]

Bulk settlement report [1/4]

---

src/Entities/Installation/FeaturesEntity.php
tests/Entities/FeaturesEntityTest.php

- Features entity `collect_fulfilment` accessor methods
[Delivers [#158838199](https://www.pivotaltracker.com/story/show/158838199)]

Collect fulfilment [2/3]

---

src/Gateways/DictionaryGateway.php
src/Gateways/SupportingDocumentGateway.php
tests/ApiClient/ProviderCsvApiClientTest.php
tests/Gateways/DictionaryGatewayTest.php
tests/Gateways/SupportingDocumentGatewayTest.php

- Added API call support for adding an uploaded document from a retailer  (#158623202)
- Added API call support for retrieving a dictionary of document types (#158623202)
[Delivers [#158623202](https://www.pivotaltracker.com/story/show/158623202)]

Supporting Documents

---

src/Entities/Installation/FeaturesEntity.php
tests/Entities/FeaturesEntityTest.php

- Added feature flag for upload documents (#159017282)
[Delivers [#159017282](https://www.pivotaltracker.com/story/show/159017282)]

Add feature

---

src/Gateways/CustomerIntelligenceGateway.php
tests/Gateways/CustomerIntelligenceGatewayTest.php

- getLeadScore api endpoint (#160168479)
[Delivers [#160168479](https://www.pivotaltracker.com/story/show/160168479)]

Lead score grid [2/2]

---

src/Entities/Application/CustomerIntelligenceEntity.php
src/Entities/ApplicationEntity.php
tests/Entities/CustomerIntelligenceEntityTest.php

- Customer Intelligence
Deliveres [#160168501](https://www.pivotaltracker.com/story/show/160168501)

Added Customer Intelligence

---

src/Entities/Installation/FeaturesEntity.php
tests/Entities/FeaturesEntityTest.php

- Added `lead_score` to Feature Entity (#160168389)
[Delivers [#160168389](https://www.pivotaltracker.com/story/show/160168389)]

Feature permission

---

src/Gateways/CustomerIntelligenceGateway.php
tests/Gateways/CustomerIntelligenceGatewayTest.php

- perform PreApproval Customer Intelligence action (#160613620)
[Delivers [#160613620](https://www.pivotaltracker.com/story/show/160613620)]

Pre approval form and perform [1/2]

---

src/Gateways/CustomerIntelligenceGateway.php
tests/Gateways/CustomerIntelligenceGatewayTest.php

- ListPreApprovals call (#160613696)
- Refactored getCustomerIntelligence to listLeadScores (#160613696)
[Delivers [#160613696](https://www.pivotaltracker.com/story/show/160613696)]

Pre approvals grid hookup [1/2]

---

src/Entities/Application/CustomerIntelligenceEntity.php
src/Gateways/CustomerIntelligenceGateway.php
tests/Entities/CustomerIntelligenceEntityTest.php
tests/Gateways/CustomerIntelligenceGatewayTest.php

- Get pre-approval call (#160763347)
[Delivers [#160763347](https://www.pivotaltracker.com/story/show/160763347)]

Pre approval details [1/2]

---

src/Entities/Application/CustomerIntelligenceEntity.php
src/Gateways/CustomerIntelligenceGateway.php
tests/Entities/CustomerIntelligenceEntityTest.php

- email address to customer intelligence entity (#161087428)
[Delivers [#161087428](https://www.pivotaltracker.com/story/show/161087428)]

Validation [1/3]

---

src/Gateways/ProductGateway.php
tests/Gateways/ProductGatewayTest.php

- product api call (#161250236)
[Delivers [#161250236](https://www.pivotaltracker.com/story/show/161250236)]

Initialise application [1/2]
